### ISSUE TITLE
Use location in webview

### ISSUE THREAD

**Issue by vcooley** [bradmartin/nativescript-advanced-webview#13]
Is it possible for to use geolocation in an advanced webview? If so could you direct me to a resource that shows how?

Thanks.

**Comment by bradmartin** [comment]
Not native geolocation. I don't think this plugin is a good fit for doing
location based events. A better approach if you need webcontent and to hook
into the webview browser events would be the core webview for Nativescript
and communicate with it via the exposed events it provides. This plugin
doesn't offer much extensibility because it's not meant to be expanded but
more so a faster implementation of showing web content in a native app with
chrome or safari and not stock webview on a device. Hope that helps some.
The native controls here just don't expose much in terms on communicating
with the web content.

**Comment by vcooley** [comment]
Great, thanks for the quick response. Since we have control of the web content we need to display, and we only need the location on load, I will probably go with a solution that involves sending the location in the URL.

**Comment by CristianHCol** [comment]
@vcooley
Could you solve this problem?.
I was trying something similar, i have a webpage and i try to access to the localization througth html5 geolocalization api (navigator.geolocalization). But never showed the prompt to permissions.

**Comment by vcooley** [comment]
@CristianHCol I ended up solving my problem by just sending the latitude and longitude in the query params. You'll have to request the location from the phone using the `nativescript-geolocation` plugin.
